#!/usr/bin/env bash

set -euo pipefail

if ! [[ -v 1 ]]; then
	echo "Usage: $0 URL" >&2
	exit 1
fi

traverse ()
{
	curl -sS $1 | hq 'a:not([href="../"]):not([href^="/"]):not([href^="?"])' attr href | {
		while read -r INDEX; do
			if [[ "$INDEX" = */ ]]; then
				traverse "${1}${INDEX}"
			else
				echo "${1}${INDEX}"
			fi
		done
	}
}

traverse $([[ "$1" = */ ]] && echo "$1" || echo "${1}/")
